config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/team', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/clients/signup', to: 'clients#new', as: 'client_signup'

  get "login", to: "sessions#new", as: "login"

  post "sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"

  resources :clients, only: [:create, :show, :edit, :update]

  resources :stylists

  delete "/appointments/:id", to: "appointments#destroy", as: "appointment_delete"

  resources :appointments, only: [:new, :create]


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def main
    render 'home'
  end

  def help
    render 'help'
  end

  def about
    render 'about'
  end

  def contact
    render 'contact'
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.erb
<div class="container center">

  <div class="section">
    <h2 class="center-align teal-text text-darken-1">About</h2>
  </div>

  <div class="section">
    <p class="flow-text">BarberBase is the premier stop for the best barbers in the world. With BarberBase, you can book an appointment with any of our master barbers. <br> <%= link_to "Create an account", client_signup_path %> today! </p>
  </div>

  <div class="section">
    <p class="flow-text">For more information, <em>or if you're a barber looking to join BarberBase</em>, email us at <a href="#">hello@barberbase.com</a> </p>
  </div>

</div>

app/views/static_pages/contact.erb
<div class="container center">

  <div class="section">
    <h2 class="center-align teal-text text-darken-1">Team</h2>
  </div>
  <div class="section">
    <h4 class="teal-text text-darken-1">Shawna Davis & Roger Vera</h4>
  </div>

  <div class="section">
      <%= image_tag "https://i.imgur.com/jq6z6ig.jpg", class: "responsive-img" %>
  </div>

</div>

app/views/static_pages/help.erb
<h1>Help Page</h1>

app/views/static_pages/home.erb
<h4 class="center-align">The Premier Site for the Best Barbers </h4>


<%= link_to "Login to your Client Account", login_path %>

<%= link_to "Sign up as a new Client", client_signup_path %>

<br>
<br>
<br>

<h4>Are you a barber and want to sign up?</h4>
<h5>Email us at <%= link_to "hello@barberbase.com", "/" %> </h5>