config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/team', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/clients/signup', to: 'clients#new', as: 'client_signup'

  get "login", to: "sessions#new", as: "login"

  post "sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"

  resources :clients, only: [:create, :show, :edit, :update]

  resources :stylists

  delete "/appointments/:id", to: "appointments#destroy", as: "appointment_delete"

  resources :appointments, only: [:new, :create]


end

app/models/client.rb
class Client < ApplicationRecord
  has_secure_password
  # validates :name, presence: true
  # validates :email, presence: true

  # validates :email, uniqueness: true

  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, format: { with: VALID_EMAIL_REGEX }

  # validates :phone_number, uniqueness: true
  has_many :appointments
  has_many :stylist_services, through: :appointments

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authorized
  skip_before_action :authorized, only: [:new, :create] # or whatever onlys we will need

  def show
    if current_user.id == params[:id].to_i
      @client = Client.find_by(id: params[:id])
    else
      # Don't allow user to view other user's profile
      # Just redirect the user to the session[:user_id] AKA current_user.id
      redirect_to client_path(current_user.id)
    end
  end

  def new
    @client = Client.new()
  end

  def create
    @client = Client.new(client_params)
    if @client.valid?
      @client.save
      flash[:new_account] = "Welcome, #{@client.name}. Please sign in."
      redirect_to @client
    else
      raise params.inspect
      redirect_to client_signup_path
    end
  end

  def edit
    if current_user.id == params[:id].to_i
      @client = Client.find_by(id: params[:id])
    else
      # Don't allow user to edit other user's profile
      # Just redirect the user to the session[:user_id] AKA current_user.id, AKA the user's show page.
      redirect_to client_path(current_user.id)
    end
  end

  def update
    @client = Client.find_by(id: params[:id])
    if @client.update(client_params)
      redirect_to client_path
    else
      redirect_to edit_client_path
    end
  end

  private

  def client_params
    params.require(:client).permit(:name, :email, :phone_number, :password, :password_confirmation)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.erb
<div class="container">
  <h4 class="center-align teal-text text-darken-1">Edit your account information</h4>

  <%= form_for @client do |f| %>
    <%= f.text_field :name, placeholder: 'Full Name', class: 'center-align' %><br>

    <%= f.text_field :email, placeholder: 'Email', class: 'center-align' %><br>

    <%= f.password_field :password, placeholder: 'Create a Password', class: 'center-align' %><br>

    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'center-align'%><br><br>
    <div class="section">
      <div class="center-align">
        <%= f.submit "Update", class: "btn teal darken-1" %>
      </div>
    </div>

  <% end %>
</div>

<div class="section">
  <div class="center-align">
    <%= link_to "Return to profile", client_path(@client) %>
  </div>
</div>

app/views/clients/new.erb
<div class="container">
  <h4 class="center-align teal-text text-darken-1">Create Account</h4>

  <%= form_for @client do |f| %>
    <%= f.text_field :name, placeholder: 'Full Name', class: 'center-align' %><br>

    <%= f.text_field :email, placeholder: 'Email', class: 'center-align' %><br>

    <%= f.password_field :password, placeholder: 'Create a Password', class: 'center-align' %><br>

    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'center-align'%><br><br>
    <div class="section">
      <div class="center-align">
        <%= f.submit "Sign Up", class: "btn teal darken-1" %>
      </div>
    </div>

  <% end %>

  <div class="section">
    <div class="center-align">
    <%= link_to "Login to existing account", login_path, class: "" %>
    </div>
  </div>

</div>

app/views/clients/show.erb
<div class="container center">

  <div class="section">
    <h2 class="center-align teal-text text-darken-1">Welcome, <%= @client.name %></h2>
  </div>

  <div class="section">
    <% if @client.appointments == [] %>
      <h6 class="red-text text-darken-1">You have no upcoming appointments!</h6>
    <% else %>
      <% if @client.appointments.count == 1 %>
      <h6 class="teal-text text-darken-1">Here's information on your next appointment:</h6>
      <% else %>
      <h6 class="teal-text text-darken-1">You have the following upcoming appointments:</h6>
      <% end %>
      <div class="section">
        <table>
          <thead>
            <tr class="teal-text text-darken-1">
                <th>Barber</th>
                <th>Service</th>
                <th>Date</th>
                <th></th>
            </tr>
          </thead>

          <tbody>
            <% @client.appointments.each do |appointment| %>
              <tr>
                <% time = appointment.start_time_display %>
                <% appoinment_info = appointment.date.strftime("%A, %m/%d/%Y at #{time}") %>
                <td> <%= appointment.stylist_name %> </td>
                <td> <%= appointment.service_title %> </td>
                <td> <%= appoinment_info %> </td>
                <td> <%= link_to "Cancel", appointment_delete_path(appointment), class: "cancel btn red darken-2
", method: :delete, data: { confirm: "Are you sure you want to cancel your appointment for #{appoinment_info}?" } %> </td>

              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>


  <div class="section">
    <h6><%= link_to "Make an New Appointment", stylists_path, class: "btn teal darken-1" %></h6>
  </div>

  <div class="section">
    <div class="row center">
      <div class="col s6">
        <%= link_to "Edit Profile", edit_client_path, class: "btn teal darken-1" %></h6>
      </div>
      <div class="col s6">
        <%= link_to "Logout", sessions_path, method: :delete, class: "btn teal darken-1"%></h6>
      </div>
    </div>
  </div>

</div>