config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/team', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/clients/signup', to: 'clients#new', as: 'client_signup'

  get "login", to: "sessions#new", as: "login"

  post "sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"

  resources :clients, only: [:create, :show, :edit, :update]

  resources :stylists

  delete "/appointments/:id", to: "appointments#destroy", as: "appointment_delete"

  resources :appointments, only: [:new, :create]


end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :stylist_services

  has_many :services, through: :stylist_services

  has_many :appointments, through: :stylist_services

  has_many :pictures
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  before_action :authorized
  before_action :find_stylist, only: [:show, :edit, :update, :destroy, :start_time_block_id]
  # skip_before_action :authorized, only: [:new, :create] # or whatever onlys we will need

  def index
    @stylists = Stylist.all
  end

  def show
    flash.delete(:errors)
    @appointment = Appointment.new
  end

  private

  def find_stylist
    @stylist = Stylist.find(params[:id])
  end
end

app/views/stylists/index.erb
<div class="container">
  <h4 class="center-align teal-text text-darken-1">Select a barber for your next appointment</h4>


  <div class="row">
  <% @stylists.each do |stylist| %>

  <div class="col s4">
    <div class="card">
      <div class="card-image">
        <%= link_to image_tag(stylist.profile_picture), stylist %>
      </div>
      <div class="card-action">
        <%= link_to stylist.name, stylist %>
      </div>
    </div>
  </div>

  <% end %>
  </div>


</div>

app/views/stylists/new.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <h5><strong><%= error %></strong>!</h5>
  <% end %>
<% end %>
<%= form_for @stylist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>
<%= f.collection_select(:start_time, BlockTable.all, :start_time_display, :start_time_display) %><br><br>

  <%= f.submit %>

<% end %>

app/views/stylists/show.erb
<div class="container">
  <div class="section">
    <div class="row">

      <div class="col s6">
        <div class="card">
          <div class="card-image">
            <%= image_tag(@stylist.profile_picture) %>
            <span class="card-title"> <%= @stylist.name %> </span>
          </div>
        </div>
      </div>

      <div class="col s6">
        <%= form_for @appointment, as: :stylist_service, url: new_appointment_path, method: :get do |f| %>

        <h4>Choose a Service</h4>
        <div class="section">
          <%= f.collection_select(:stylist_service_id, @stylist.stylist_services, :id, :title_and_duration, class: "browser-default") %>
        </div>
        <div class="section">
          <%= f.submit class: "btn teal darken-1" %>
        </div>

        <% end %>
      </div>
    </div>
    <!-- End Row -->
  </div>
    <h4 class="center-align"> <%= @stylist.name %>'s Work </h4>
    <div class="row">
      <% @stylist.pictures.each do |picture| %>

      <div class="col s4">
        <div class="card">
          <div class="card-image">
            <%= image_tag picture.url %>
          </div>
        </div>
      </div>

      <% end %>
    </div>

  <!-- End Section -->
  <div class="section">
    <div class="center-align">
      <%= link_to "Back to all stylists", stylists_path %>
    </div>
  </div>
  <!-- End Section -->
</div>
<!-- End Containter -->
<script type="text/javascript">
  var elems = document.querySelectorAll('select');
  var instances = M.FormSelect.init(elems, {})
</script>