config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/team', to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/clients/signup', to: 'clients#new', as: 'client_signup'

  get "login", to: "sessions#new", as: "login"

  post "sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"

  resources :clients, only: [:create, :show, :edit, :update]

  resources :stylists

  delete "/appointments/:id", to: "appointments#destroy", as: "appointment_delete"

  resources :appointments, only: [:new, :create]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barberbase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="zcontainer">  <!-- newly added code -->
    <nav>
      <div class="nav-wrapper teal darken-1">
        <%= link_to "BarberBase", root_path, class: "brand-logo left", id: "logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Team", team_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Request Appointment", stylists_path %></li>
            <li><%= link_to "My Profile", client_path(current_user.id) %></li>
          <% end %>
        </ul>
      </div>
    </nav>
      <%= yield %>
    </div>                   <!-- newly added code -->
  </body>
</html>